### ISSUE TITLE
java.lang.IllegalStateException: The property does not exist as it has no key, value, or associated element

### ISSUE THREAD

**Issue by zhou5791759** [twilmes/sql-gremlin#11]
Caused by: java.lang.IllegalStateException: The property does not exist as it has no key, value, or associated element
    at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.propertyDoesNotExist(Property.java:151)
    at org.apache.tinkerpop.gremlin.structure.util.empty.EmptyVertexProperty.value(EmptyVertexProperty.java:74)
    at org.twilmes.sql.gremlin.processor.SingleQueryExecutor.run(SingleQueryExecutor.java:92)
    at org.twilmes.sql.gremlin.processor.GremlinCompiler.execute(GremlinCompiler.java:119)
    at org.twilmes.sql.gremlin.plugin.SqlRemoteAcceptor.submit(SqlRemoteAcceptor.java:94)

SingleQueryExecutor

 /*
 vertex does not contain attributes that are abnormal.
      } else if (!(res.property(propName) instanceof EmptyProperty)
 */

 } else if (res.properties(propName).hasNext()) {

**Comment by twilmes** [comment]
Thanks for reporting Zhou.  Can you provide your schema file and the SQL query you ran?  Or if not the whole file, at least the portions that are relevant to the query?

**Comment by zhou5791759** [comment]
--schema.json
--(pwd:/home/hadoop/conf/schema.json)

{
    "tables": [
    {
      "name": "human",
      "columns": [
        {"name": "name", "type": "string"},
        {"name": "gender", "type": "string"}
      ]
    }
    ],
    "relationships": []
}

--execute script:

graph = TitanFactory.open('conf/hbase.properties')

g = graph.traversal()

configFn = "/home/hadoop/conf/schema.json"

:remote connect sql.gremlin graph configFn

:> select \* from human

--exception:
Caused by: java.lang.IllegalStateException: The property does not exist as it has no key, value, or associated element
at org.apache.tinkerpop.gremlin.structure.Property$Exceptions.propertyDoesNotExist(Property.java:151)
at org.apache.tinkerpop.gremlin.structure.util.empty.EmptyVertexProperty.value(EmptyVertexProperty.java:74)
at org.twilmes.sql.gremlin.processor.SingleQueryExecutor.run(SingleQueryExecutor.java:92)
at org.twilmes.sql.gremlin.processor.GremlinCompiler.execute(GremlinCompiler.java:119)
at org.twilmes.sql.gremlin.plugin.SqlRemoteAcceptor.submit(SqlRemoteAcceptor.java:94)

**Comment by zhou5791759** [comment]
The above update is my input !!
